name: cats-project

services:
  cats_go_api:
    build: ./cats-go-api
    container_name: cats-go-api
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    depends_on:
      cats_database:
        condition: service_healthy

  cats_java_api:
    build: ./cats-java-api
    container_name: cats-java-api
    ports:
      - "8002:8002"
    env_file:
      - ./.env
    depends_on:
      cats_database:
        condition: service_healthy

  cats_node_api:
    build: ./cats-node-api
    container_name: cats-node-api
    ports:
      - "8003:8003"
    env_file:
      - ./.env
    depends_on:
      cats_database:
        condition: service_healthy

  cats_python_api:
    build: ./cats-python-api
    container_name: cats-python-api
    ports:
      - "8004:8004"
    env_file:
      - ./.env
    depends_on:
      cats_database:
        condition: service_healthy
    volumes:
      - ./cats-python-api:/app
    command: python manage.py runserver 0.0.0.0:8004

  cats_kotlin_api:
    build: ./cats-kotlin-api
    container_name: cats-kotlin-api
    ports:
      - "8005:8005"
    env_file:
      - ./.env
    depends_on:
      cats_database:
        condition: service_healthy

  cats_database:
    image: postgres:15
    container_name: cats-database
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: